-- Persistent Data
local multiRefObjects = {

} -- multiRefObjects
local obj1 = {
	["classes"] = {
		[1] = false;
		[2] = true;
		[3] = false;
		[4] = false;
		[5] = false;
		[6] = false;
		[7] = false;
		[8] = false;
		[9] = false;
		[10] = false;
		[11] = false;
		[12] = false;
		[13] = false;
		[14] = false;
		[15] = false;
		[16] = false;
		[17] = false;
		[18] = false;
		[19] = false;
		[20] = true;
		[21] = false;
		[22] = false;
		[23] = false;
		[24] = false;
		[25] = false;
		[26] = false;
		[27] = false;
		[28] = false;
		[29] = false;
		[30] = false;
		[31] = false;
		[32] = false;
		[33] = false;
		[34] = false;
		[35] = false;
		[36] = false;
		[37] = false;
		[38] = false;
		[39] = false;
		[40] = false;
	};
	["filters"] = {
		[1] = "Stance Fire/Earth";
		[2] = "AOE On/Off";
		[3] = "";
		[4] = "";
		[5] = "";
	};
	["mingp"] = 0;
	["priosystem"] = false;
	["skills"] = {
		[1] = {
			["gcd"] = "False";
			["gcdtime"] = 0;
			["id"] = 70;
			["ignoremoving"] = true;
			["levelmin"] = 30;
			["maxRange"] = 0;
			["name"] = "Rockbreaker";
			["pbuff"] = "109";
			["prio"] = 1;
			["tarange"] = 5;
			["tecenter"] = "Self";
			["tecount"] = 3;
			["terange"] = 6;
			["trg"] = "Player";
		};
		[2] = {
			["gcd"] = "False";
			["gcdtime"] = 0;
			["id"] = 66;
			["ignoremoving"] = true;
			["levelmin"] = 30;
			["maxRange"] = 3;
			["name"] = "Demolish";
			["pbuff"] = "109";
			["prio"] = 2;
			["thpadv"] = 1;
			["tnbuff"] = "246";
			["tnbuffdura"] = 5;
		};
		[3] = {
			["gcd"] = "False";
			["gcdtime"] = 0;
			["id"] = 56;
			["ignoremoving"] = true;
			["levelmin"] = 6;
			["maxRange"] = 3;
			["name"] = "Snap Punch";
			["pbuff"] = "109";
			["prio"] = 3;
		};
		[4] = {
			["gcd"] = "False";
			["gcdtime"] = 0;
			["id"] = 16473;
			["ignoremoving"] = true;
			["levelmin"] = 45;
			["maxRange"] = 0;
			["name"] = "Four-point Fury";
			["pbuff"] = "108";
			["prio"] = 4;
			["tarange"] = 5;
			["tecenter"] = "Self";
			["tecount"] = 3;
			["terange"] = 6;
			["trg"] = "Player";
		};
		[5] = {
			["gcd"] = "False";
			["gcdtime"] = 0;
			["id"] = 61;
			["ignoremoving"] = true;
			["levelmin"] = 18;
			["maxRange"] = 3;
			["name"] = "Twin Snakes";
			["pbuff"] = "108";
			["pnbuff"] = "3001";
			["pnbuffdura"] = 5;
			["prio"] = 5;
		};
		[6] = {
			["gcd"] = "False";
			["gcdtime"] = 0;
			["id"] = 54;
			["ignoremoving"] = true;
			["levelmin"] = 4;
			["maxRange"] = 3;
			["name"] = "True Strike";
			["pbuff"] = "108";
			["prio"] = 6;
		};
		[7] = {
			["gcd"] = "False";
			["gcdtime"] = 0;
			["id"] = 62;
			["ignoremoving"] = true;
			["levelmin"] = 26;
			["maxRange"] = 0;
			["name"] = "Arm of the Destroyer";
			["pbuff"] = "107";
			["prio"] = 7;
			["tarange"] = 5;
			["tecenter"] = "Self";
			["tecount"] = 3;
			["terange"] = 6;
			["trg"] = "Player";
		};
		[8] = {
			["gcd"] = "False";
			["gcdtime"] = 0;
			["id"] = 53;
			["ignoremoving"] = true;
			["levelmin"] = 1;
			["maxRange"] = 3;
			["name"] = "Bootshine";
			["pbuff"] = "1861";
			["prio"] = 8;
		};
		[9] = {
			["gcd"] = "False";
			["gcdtime"] = 0;
			["id"] = 74;
			["ignoremoving"] = true;
			["levelmin"] = 50;
			["maxRange"] = 3;
			["name"] = "Dragon Kick";
			["prio"] = 9;
		};
		[10] = {
			["gcd"] = "True";
			["id"] = 25763;
			["ignoremoving"] = true;
			["levelmin"] = 15;
			["maxRange"] = 0;
			["name"] = "Howling Fist";
			["prio"] = 10;
			["tarange"] = 10;
			["tecenter"] = "Target";
			["tecount"] = 4;
			["terange"] = 6;
		};
		[11] = {
			["gcd"] = "True";
			["id"] = 3547;
			["ignoremoving"] = true;
			["levelmin"] = 15;
			["maxRange"] = 0;
			["name"] = "The Forbidden Chakra";
			["prio"] = 11;
		};
		[12] = {
			["gcd"] = "True";
			["id"] = 7395;
			["ignoremoving"] = true;
			["levelmin"] = 68;
			["maxRange"] = 0;
			["name"] = "Riddle of Fire";
			["prio"] = 12;
			["trg"] = "Player";
		};
		[13] = {
			["gcd"] = "True";
			["id"] = 65;
			["ignoremoving"] = true;
			["levelmin"] = 42;
			["maxRange"] = 0;
			["name"] = "Mantra";
			["phpb"] = 80;
			["prio"] = 13;
			["tarange"] = 15;
			["terange"] = 15;
			["trg"] = "Player";
		};
		[14] = {
			["gcd"] = "True";
			["id"] = 7542;
			["ignoremoving"] = true;
			["levelmin"] = 12;
			["maxRange"] = 0;
			["name"] = "Bloodbath";
			["phpb"] = 65;
			["prio"] = 14;
			["trg"] = "Player";
		};
		[15] = {
			["gcd"] = "True";
			["id"] = 7541;
			["ignoremoving"] = true;
			["levelmin"] = 8;
			["maxRange"] = 0;
			["name"] = "Second Wind";
			["phpb"] = 50;
			["prio"] = 15;
			["trg"] = "Player";
		};
		[16] = {
			["combat"] = "Out of Combat";
			["gcd"] = "False";
			["gcdtime"] = 0;
			["id"] = 4262;
			["ignoremoving"] = true;
			["levelmin"] = 52;
			["maxRange"] = 0;
			["name"] = "Form Shift";
			["pnbuff"] = "107+108+109+2513";
			["prio"] = 16;
			["trg"] = "Player";
		};
		[17] = {
			["combat"] = "Out of Combat";
			["gcd"] = "False";
			["gcdtime"] = 0;
			["id"] = 3546;
			["ignoremoving"] = true;
			["levelmin"] = 15;
			["maxRange"] = 0;
			["name"] = "Meditation";
			["prio"] = 17;
			["secspassed"] = 5;
			["secspassedu"] = 5;
			["trg"] = "Player";
		};
	};
	["update"] = 20190807;
	["version"] = 3;
}
return obj1
