-- Persistent Data
local multiRefObjects = {

} -- multiRefObjects
local obj1 = {
	["classes"] = {
		[1] = false;
		[2] = true;
		[3] = false;
		[4] = false;
		[5] = false;
		[6] = false;
		[7] = false;
		[8] = false;
		[9] = false;
		[10] = false;
		[11] = false;
		[12] = false;
		[13] = false;
		[14] = false;
		[15] = false;
		[16] = false;
		[17] = false;
		[18] = false;
		[19] = false;
		[20] = true;
		[21] = false;
		[22] = false;
		[23] = false;
		[24] = false;
		[25] = false;
		[26] = false;
		[27] = false;
		[28] = false;
		[29] = false;
		[30] = false;
		[31] = false;
		[32] = false;
		[33] = false;
		[34] = false;
		[35] = false;
		[36] = false;
	};
	["filters"] = {
		[1] = "No Buffs/Debuffs";
		[2] = "Diversion Off";
		[3] = "";
		[4] = "";
		[5] = "";
	};
	["skills"] = {
		[1] = {
			["dobuff"] = true;
			["gcd"] = "False";
			["gcdtime"] = 0;
			["id"] = 7394;
			["ignoremoving"] = true;
			["levelmin"] = 64;
			["maxRange"] = 0;
			["name"] = "Riddle of Earth";
			["prio"] = 1;
			["tcastids"] = "11290,11291";
			["trg"] = "Player";
		};
		[2] = {
			["combat"] = "Any";
			["gcd"] = "False";
			["gcdtime"] = 0;
			["id"] = 63;
			["ignoremoving"] = true;
			["levelmin"] = 40;
			["maxRange"] = 0;
			["name"] = "Fists of Fire";
			["pnbuff"] = "103+1179";
			["prio"] = 2;
			["trg"] = "Player";
		};
		[3] = {
			["gauge1lt"] = 2;
			["gcd"] = "False";
			["id"] = 56;
			["ignoremoving"] = true;
			["levelmin"] = 6;
			["maxRange"] = 3;
			["name"] = "Snap Punch";
			["pbuff"] = "110";
			["prio"] = 3;
		};
		[4] = {
			["gauge3lt"] = 8;
			["gcd"] = "False";
			["id"] = 56;
			["ignoremoving"] = true;
			["levelmin"] = 6;
			["maxRange"] = 3;
			["name"] = "Snap Punch";
			["pbuff"] = "110";
			["prio"] = 4;
		};
		[5] = {
			["gcd"] = "False";
			["id"] = 61;
			["ignoremoving"] = true;
			["levelmin"] = 18;
			["maxRange"] = 3;
			["name"] = "Twin Snakes";
			["pbuff"] = "110";
			["pnbuff"] = "101";
			["pnbuffdura"] = 5;
			["prio"] = 5;
		};
		[6] = {
			["gcd"] = "False";
			["id"] = 74;
			["ignoremoving"] = true;
			["levelmin"] = 50;
			["maxRange"] = 3;
			["name"] = "Dragon Kick";
			["pbuff"] = "110";
			["prio"] = 6;
			["tnbuff"] = "821";
			["tnbuffdura"] = 5;
			["tnbuffowner"] = "Any";
		};
		[7] = {
			["gcd"] = "False";
			["id"] = 53;
			["ignoremoving"] = true;
			["levelmin"] = 1;
			["maxRange"] = 3;
			["name"] = "Bootshine";
			["pbuff"] = "110";
			["prio"] = 7;
		};
		[8] = {
			["filterone"] = "Off";
			["gcd"] = "False";
			["id"] = 66;
			["ignoremoving"] = true;
			["levelmin"] = 30;
			["maxRange"] = 3;
			["name"] = "Demolish";
			["prio"] = 8;
			["thpadv"] = 5;
			["tnbuff"] = "246";
			["tnbuffdura"] = 5;
		};
		[9] = {
			["gcd"] = "False";
			["id"] = 56;
			["ignoremoving"] = true;
			["levelmin"] = 6;
			["maxRange"] = 3;
			["name"] = "Snap Punch";
			["prio"] = 9;
		};
		[10] = {
			["filterone"] = "Off";
			["gcd"] = "False";
			["id"] = 61;
			["ignoremoving"] = true;
			["levelmin"] = 18;
			["maxRange"] = 3;
			["name"] = "Twin Snakes";
			["pnbuff"] = "101";
			["pnbuffdura"] = 5;
			["prio"] = 10;
		};
		[11] = {
			["gcd"] = "False";
			["id"] = 54;
			["ignoremoving"] = true;
			["levelmin"] = 4;
			["maxRange"] = 3;
			["name"] = "True Strike";
			["prio"] = 11;
		};
		[12] = {
			["filterone"] = "Off";
			["gcd"] = "False";
			["id"] = 74;
			["ignoremoving"] = true;
			["levelmin"] = 50;
			["maxRange"] = 3;
			["name"] = "Dragon Kick";
			["pbuff"] = "107";
			["prio"] = 12;
			["tnbuff"] = "821";
			["tnbuffdura"] = 5;
			["tnbuffowner"] = "Any";
		};
		[13] = {
			["gcd"] = "False";
			["id"] = 53;
			["ignoremoving"] = true;
			["levelmin"] = 1;
			["maxRange"] = 3;
			["name"] = "Bootshine";
			["prio"] = 13;
		};
		[14] = {
			["gauge1lt"] = 1;
			["gcd"] = "True";
			["gcdtime"] = 0.80000001192093;
			["id"] = 69;
			["ignoremoving"] = true;
			["levelmin"] = 50;
			["maxRange"] = 0;
			["name"] = "Perfect Balance";
			["prio"] = 14;
			["trg"] = "Player";
		};
		[15] = {
			["gcd"] = "True";
			["gcdtime"] = 0.80000001192093;
			["id"] = 7541;
			["ignoremoving"] = true;
			["levelmin"] = 8;
			["maxRange"] = 0;
			["name"] = "Second Wind";
			["phpb"] = 50;
			["prio"] = 15;
			["trg"] = "Player";
		};
		[16] = {
			["gcd"] = "True";
			["gcdtime"] = 0.80000001192093;
			["id"] = 59;
			["ignoremoving"] = true;
			["levelmin"] = 10;
			["maxRange"] = 0;
			["name"] = "Internal Release";
			["prio"] = 16;
			["trg"] = "Player";
		};
		[17] = {
			["gcd"] = "True";
			["gcdtime"] = 0.80000001192093;
			["id"] = 7396;
			["ignoremoving"] = true;
			["levelmin"] = 70;
			["maxRange"] = 0;
			["name"] = "Brotherhood";
			["prio"] = 17;
			["tarange"] = 15;
			["terange"] = 15;
			["trg"] = "Player";
		};
		[18] = {
			["gcd"] = "True";
			["gcdtime"] = 0.80000001192093;
			["id"] = 7395;
			["ignoremoving"] = true;
			["levelmin"] = 68;
			["maxRange"] = 0;
			["name"] = "Riddle of Fire";
			["npskill"] = "7394";
			["pnbuff"] = "110+1179";
			["prio"] = 18;
			["trg"] = "Player";
		};
		[19] = {
			["gcd"] = "True";
			["gcdtime"] = 0.80000001192093;
			["id"] = 7542;
			["ignoremoving"] = true;
			["levelmin"] = 32;
			["maxRange"] = 0;
			["name"] = "Bloodbath";
			["phpb"] = 75;
			["prio"] = 19;
			["trg"] = "Player";
		};
		[20] = {
			["gauge2eq"] = 5;
			["gcd"] = "True";
			["gcdtime"] = 0.80000001192093;
			["id"] = 3547;
			["ignoremoving"] = true;
			["levelmin"] = 54;
			["maxRange"] = 0;
			["name"] = "The Forbidden Chakra";
			["prio"] = 20;
		};
		[21] = {
			["gcd"] = "True";
			["gcdtime"] = 0.80000001192093;
			["id"] = 3545;
			["ignoremoving"] = true;
			["levelmin"] = 56;
			["maxRange"] = 0;
			["name"] = "Elixir Field";
			["prio"] = 21;
			["tarange"] = 5;
			["terange"] = 5;
			["trg"] = "Player";
		};
		[22] = {
			["gcd"] = "True";
			["gcdtime"] = 0.80000001192093;
			["id"] = 67;
			["ignoremoving"] = true;
			["levelmin"] = 46;
			["maxRange"] = 10;
			["name"] = "Howling Fist";
			["prio"] = 22;
			["tarange"] = 10;
			["terange"] = 10;
		};
		[23] = {
			["gcd"] = "True";
			["gcdtime"] = 0.80000001192093;
			["id"] = 64;
			["ignoremoving"] = true;
			["levelmin"] = 38;
			["maxRange"] = 3;
			["name"] = "Steel Peak";
			["prio"] = 23;
		};
		[24] = {
			["charge"] = true;
			["gcd"] = "True";
			["gcdtime"] = 0.80000001192093;
			["id"] = 71;
			["ignoremoving"] = true;
			["levelmin"] = 35;
			["maxRange"] = 20;
			["name"] = "Fire Tackle";
			["prio"] = 24;
		};
		[25] = {
			["gcd"] = "True";
			["gcdtime"] = 0.80000001192093;
			["id"] = 7546;
			["ignoremoving"] = true;
			["levelmin"] = 48;
			["maxRange"] = 0;
			["name"] = "True North";
			["prio"] = 25;
			["trg"] = "Player";
		};
		[26] = {
			["gcd"] = "True";
			["gcdtime"] = 0.80000001192093;
			["id"] = 7544;
			["ignoremoving"] = true;
			["levelmin"] = 24;
			["maxRange"] = 0;
			["name"] = "Invigorate";
			["prio"] = 26;
			["ptpb"] = 500;
			["trg"] = "Player";
		};
		[27] = {
			["filtertwo"] = "Off";
			["gcd"] = "True";
			["gcdtime"] = 0.80000001192093;
			["id"] = 7545;
			["ignoremoving"] = true;
			["levelmin"] = 20;
			["maxRange"] = 0;
			["name"] = "Diversion";
			["prio"] = 27;
			["thpadv"] = 5;
			["trg"] = "Player";
		};
		[28] = {
			["combat"] = "Out of Combat";
			["gauge2lt"] = 4;
			["gcd"] = "False";
			["id"] = 3546;
			["ignoremoving"] = true;
			["levelmin"] = 54;
			["maxRange"] = 0;
			["name"] = "Meditation";
			["prio"] = 28;
			["secspassedu"] = 1.7000000476837;
			["trg"] = "Player";
		};
	};
	["version"] = 3;
}
return obj1
