-- Persistent Data
local multiRefObjects = {

} -- multiRefObjects
local obj1 = {
	["classes"] = {
		[1] = false;
		[2] = false;
		[3] = false;
		[4] = false;
		[5] = false;
		[6] = false;
		[7] = false;
		[8] = false;
		[9] = false;
		[10] = false;
		[11] = false;
		[12] = false;
		[13] = false;
		[14] = false;
		[15] = false;
		[16] = false;
		[17] = false;
		[18] = false;
		[19] = false;
		[20] = false;
		[21] = false;
		[22] = false;
		[23] = false;
		[24] = false;
		[25] = false;
		[26] = false;
		[27] = false;
		[28] = true;
		[29] = false;
		[30] = false;
		[31] = false;
		[32] = false;
		[33] = false;
		[34] = false;
		[35] = false;
		[36] = false;
	};
	["filters"] = {
		[1] = "Pet Type";
		[2] = "";
		[3] = "";
		[4] = "";
		[5] = "";
	};
	["skills"] = {
		[1] = {
			["combat"] = "Any";
			["gcd"] = "True";
			["gcdtime"] = 0.5;
			["hprio1"] = "Self";
			["hprio2"] = "Tank";
			["hprio3"] = "Party";
			["hpriohp"] = 50;
			["id"] = 189;
			["ignoremoving"] = true;
			["levelmin"] = 50;
			["name"] = "Lustrate";
			["playerlevelmin"] = 50;
			["prio"] = 1;
			["trg"] = "Heal Priority";
			["trgself"] = true;
		};
		[2] = {
			["combat"] = "Any";
			["gcd"] = "True";
			["gcdtime"] = 0.5;
			["id"] = 3583;
			["ignoremoving"] = true;
			["levelmin"] = 52;
			["maxRange"] = 0;
			["name"] = "Indomitability";
			["phpb"] = 70;
			["playerlevelmin"] = 52;
			["prio"] = 2;
			["pthpb"] = 70;
			["trg"] = "Player";
		};
		[3] = {
			["combat"] = "Any";
			["gcdtime"] = 0;
			["id"] = 7561;
			["ignoremoving"] = true;
			["levelmin"] = 32;
			["maxRange"] = 0;
			["name"] = "Swiftcast";
			["prio"] = 3;
			["trg"] = "Dead Party";
		};
		[4] = {
			["combat"] = "Any";
			["gcdtime"] = 0.5;
			["id"] = 173;
			["ignoremoving"] = true;
			["name"] = "Resurrection";
			["playerlevelmin"] = 18;
			["prio"] = 4;
			["secspassed"] = 2;
			["tbuffowner"] = "Any";
			["trg"] = "Dead Party";
		};
		[5] = {
			["alias"] = "----- Pet -----";
			["gcdtime"] = 0.5;
			["levelmin"] = 30;
			["maxRange"] = 30;
			["prio"] = 5;
			["used"] = false;
		};
		[6] = {
			["combat"] = "Any";
			["filterone"] = "On";
			["gcdtime"] = 0.5;
			["id"] = 165;
			["name"] = "Summon";
			["playerlevelmin"] = 4;
			["pmppl"] = 10;
			["prio"] = 6;
			["trg"] = "Pet";
		};
		[7] = {
			["combat"] = "Any";
			["condition"] = "";
			["filterone"] = "Off";
			["gcdtime"] = 0.5;
			["id"] = 170;
			["name"] = "Summon II";
			["playerlevelmin"] = 15;
			["pmppl"] = 10;
			["prio"] = 7;
			["trg"] = "Pet";
		};
		[8] = {
			["alias"] = "----- OGCDs -----";
			["gcdtime"] = 0.5;
			["levelmin"] = 30;
			["maxRange"] = 30;
			["prio"] = 8;
			["used"] = false;
		};
		[9] = {
			["combat"] = "Any";
			["dobuff"] = true;
			["gauge1or"] = "0";
			["gcd"] = "True";
			["gcdtime"] = 0.5;
			["id"] = 166;
			["ignoremoving"] = true;
			["name"] = "Aetherflow";
			["playerlevelmin"] = 6;
			["pnbuff"] = "304";
			["prio"] = 9;
			["trg"] = "Player";
		};
		[10] = {
			["gcd"] = "True";
			["gcdtime"] = 0.5;
			["id"] = 7436;
			["ignoremoving"] = true;
			["levelmin"] = 66;
			["maxRange"] = 25;
			["name"] = "Chain Stratagem";
			["prio"] = 10;
		};
		[11] = {
			["gauge1eq"] = 3;
			["gcd"] = "True";
			["gcdtime"] = 0.5;
			["id"] = 167;
			["ignoremoving"] = true;
			["levelmin"] = 6;
			["maxRange"] = 25;
			["name"] = "Energy Drain";
			["ncurrentaction"] = "166";
			["npskill"] = "166";
			["prio"] = 11;
			["skncdtimemax"] = 50;
			["sknoffcd"] = "166";
		};
		[12] = {
			["condition"] = "";
			["gauge1eq"] = 2;
			["gcd"] = "True";
			["gcdtime"] = 0.5;
			["id"] = 167;
			["ignoremoving"] = true;
			["name"] = "Energy Drain";
			["playerlevelmin"] = 6;
			["prio"] = 12;
			["ptrg"] = "Enemy";
			["skncdtimemax"] = 30;
			["sknoffcd"] = "166";
		};
		[13] = {
			["condition"] = "";
			["gcd"] = "True";
			["gcdtime"] = 0.5;
			["id"] = 167;
			["ignoremoving"] = true;
			["name"] = "Energy Drain";
			["playerlevelmin"] = 6;
			["prio"] = 13;
			["ptrg"] = "Enemy";
			["skncdtimemax"] = 15;
			["sknoffcd"] = "166";
		};
		[14] = {
			["gcd"] = "True";
			["gcdtime"] = 0.5;
			["id"] = 179;
			["ignoremoving"] = true;
			["levelmin"] = 50;
			["maxRange"] = 25;
			["name"] = "Shadow Flare";
			["prio"] = 14;
			["tarange"] = 5;
			["terange"] = 5;
		};
		[15] = {
			["gcd"] = "True";
			["gcdtime"] = 0.5;
			["id"] = 7562;
			["ignoremoving"] = true;
			["levelmin"] = 24;
			["maxRange"] = 0;
			["name"] = "Lucid Dreaming";
			["pmppb"] = 60;
			["prio"] = 15;
			["trg"] = "Player";
		};
		[16] = {
			["gcd"] = "True";
			["gcdtime"] = 0.80000001192093;
			["id"] = 7567;
			["ignoremoving"] = true;
			["levelmin"] = 8;
			["maxRange"] = 0;
			["name"] = "Cleric Stance";
			["pgskill"] = "164,178,172";
			["prio"] = 16;
			["trg"] = "Player";
		};
		[17] = {
			["gcd"] = "True";
			["gcdtime"] = 0.80000001192093;
			["id"] = 176;
			["ignoremoving"] = true;
			["levelmin"] = 42;
			["maxRange"] = 25;
			["name"] = "Rouse";
			["pgskill"] = "178,164,172";
			["prio"] = 17;
			["trg"] = "Pet";
		};
		[18] = {
			["alias"] = "----- Heals -----";
			["gcdtime"] = 0.5;
			["levelmin"] = 30;
			["maxRange"] = 30;
			["prio"] = 18;
			["used"] = false;
		};
		[19] = {
			["combat"] = "Any";
			["gcdtime"] = 0.5;
			["id"] = 7568;
			["levelmin"] = 20;
			["maxRange"] = 30;
			["name"] = "Esuna";
			["prio"] = 19;
			["ptbuff"] = "7,620";
			["removebuff"] = true;
			["trg"] = "PartyS";
			["trgself"] = true;
		};
		[20] = {
			["combat"] = "Any";
			["condition"] = "";
			["gcdtime"] = 0.5;
			["hprio1"] = "Self";
			["hprio2"] = "Tank";
			["hprio3"] = "Party";
			["hpriohp"] = 66;
			["id"] = 190;
			["name"] = "Physick";
			["playerlevelmin"] = 4;
			["prio"] = 20;
			["trg"] = "Heal Priority";
		};
		[21] = {
			["combat"] = "Any";
			["dobuff"] = true;
			["gcdtime"] = 0.5;
			["id"] = 7572;
			["name"] = "Protect";
			["prio"] = 21;
			["ptnbuff"] = "146";
			["secspassedu"] = 2;
			["tnbuff"] = "146";
			["tnbuffdura"] = 300;
			["trg"] = "PartyS";
			["trgself"] = true;
		};
		[22] = {
			["alias"] = "----- Single Target -----";
			["gcdtime"] = 0.5;
			["levelmin"] = 30;
			["maxRange"] = 30;
			["prio"] = 22;
			["used"] = false;
		};
		[23] = {
			["dobuff"] = true;
			["gcdtime"] = 0.5;
			["id"] = 178;
			["ignoremoving"] = true;
			["name"] = "Bio II";
			["playerlevelmin"] = 26;
			["pmppl"] = 15;
			["prio"] = 23;
			["thpadv"] = 7;
			["tnbuff"] = "189";
			["tnbuffdura"] = 1;
		};
		[24] = {
			["dobuff"] = true;
			["gcdtime"] = 0.5;
			["id"] = 164;
			["ignoremoving"] = true;
			["name"] = "Bio";
			["playerlevelmin"] = 2;
			["pmppl"] = 15;
			["prio"] = 24;
			["thpadv"] = 7;
			["tnbuff"] = "179";
			["tnbuffdura"] = 1;
			["tncontids"] = "1798,3461,3464";
		};
		[25] = {
			["dobuff"] = true;
			["gcdtime"] = 0.5;
			["id"] = 168;
			["name"] = "Miasma";
			["playerlevelmin"] = 10;
			["pmppl"] = 15;
			["prio"] = 25;
			["thpadv"] = 7;
			["tnbuff"] = "180";
			["tnbuffdura"] = 2;
			["tncontids"] = "1798,3461,3464";
		};
		[26] = {
			["gcdtime"] = 0.5;
			["id"] = 7435;
			["levelmin"] = 64;
			["maxRange"] = 25;
			["name"] = "Broil II";
			["pmppl"] = 15;
			["prio"] = 26;
		};
		[27] = {
			["condition"] = "";
			["gcdtime"] = 0.5;
			["id"] = 3584;
			["name"] = "Broil";
			["playerlevelmin"] = 54;
			["pmppl"] = 15;
			["prio"] = 27;
		};
		[28] = {
			["gcdtime"] = 0.5;
			["id"] = 163;
			["name"] = "Ruin";
			["playerlevelmin"] = 1;
			["pmppl"] = 15;
			["prio"] = 28;
		};
		[29] = {
			["condition"] = "";
			["gcdtime"] = 0.5;
			["id"] = 172;
			["ignoremoving"] = true;
			["name"] = "Ruin II";
			["playerlevelmin"] = 38;
			["pmppl"] = 15;
			["prio"] = 29;
		};
	};
	["update"] = 20190307;
	["version"] = 3;
}
return obj1
